###   MONITORING TOOL (NAGIOS) ###
### FOR UBUNTU ###
- name: Dependencies and Libraries needed for Nagios (Ubuntu)
  tags: dependencies, libraries
  apt:
    name:
      - autoconf
      - gcc
      - libc6
      - make
      - wget
      - unzip
      - apache2
      - php
      - libapache2-mod-php7.4
      - libgd-dev
      - openssl
      - libssl-dev
      - autoconf
      - libc6
      - libmcrypt-dev
      - make
      - libssl-dev
      - wget
      - bc
      - gawk
      - dc
      - build-essential
      - snmp
      - libnet-snmp-perl
      - gettext
      - python3-pip
      - python3
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install passlib python package (Ubuntu)
  pip:
    name: passlib
  when: ansible_distribution == "Ubuntu"

- name: create a directory for nagios (Ubuntu)
  file:
    path: ~/nagios
    state: directory
  when: ansible_distribution == "Ubuntu"

- name: Nagios Download (Ubuntu)
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0755
    owner: root
    group: root
  when: ansible_distribution == "Ubuntu"


- name: Compiling nagios and adding groups(Ubuntu)
  shell: |
    cd ~/nagios/nagioscore-**
    sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
    sudo make all
    sudo make install-groups-users
    sudo usermod -a -G nagios www-data
    sudo make install
    sudo make install-daemoninit
    sudo make install-commandmode
    sudo make install-config
    sudo make install-webconf
    sudo a2enmod rewrite
    sudo a2enmod cgi
  when: ansible_distribution == "Ubuntu"

- name: Downloading nagios plugins(Ubuntu)
  unarchive:
    src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0755
    owner: root
    group: root
  when: ansible_distribution == "Ubuntu"

- name: Nagios Plugins installation (Ubuntu)
  shell: |
    cd ~/nagios/nagios-plugins*
    ./tools/setup
    ./configure
    make
    make install
  when: ansible_distribution == "Ubuntu"

- name: creating user and password (Ubuntu)
  community.general.htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: 1234
  when: ansible_distribution == "Ubuntu"

- name: starting and enabling nagios (Ubuntu)
  service:
    name: nagios
    state: restarted
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: starting and enabling apache (Ubuntu)
  service:
    name:  apache2
    state: restarted
    enabled: true
  when: ansible_distribution == "Ubuntu"

### FOR CENTOS ###
- name: Dependencies and Libraries needed for Nagios (CentOS)
  tags: dependencies, libraries
  dnf:
    name:
      - gcc
      - glibc
      - glibc-common
      - perl
      - httpd
      - php
      - wget
      - gd
      - gd-devel
      - openssl-devel
      - gcc
      - glibc
      - glibc-common
      - make
      - gettext
      - automake
      - autoconf
      - wget
      - net-snmp
      - net-snmp-utils
      - python3-pip
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install passlib python package (CentOS)
  pip:
    name: passlib
  when: ansible_distribution == "CentOS"

- name: create a directory for nagios (CentOS)
  file:
    path: ~/nagios
    state: directory
  when: ansible_distribution == "CentOS"

- name: Nagios Download (CentOS)
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0777
    owner: root
    group: root
  when: ansible_distribution == "CentOS"

- name: Compiling nagios and adding groups(CentOS)
  shell: |
    cd ~/nagios/nagioscore-**
    ./configure
    make all
    make install-groups-users
    usermod -a -G nagios apache
    make install
    make install-daemoninit
    make install-commandmode
    make install-config
    make install-webconf
  when: ansible_distribution == "CentOS"

- name: Downloading nagios plugins(CentOS)
  unarchive:
    src: https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
    dest: ~/nagios
    remote_src: yes
    mode: 0777
    owner: root
    group: root
  when: ansible_distribution == "CentOS"

- name: Nagios Plugins installation (CentOS)
  shell: |
    cd ~/nagios/nagios-plugins*
    ./tools/setup
    ./configure
    make
    make install
  when: ansible_distribution == "CentOS"

- name: creating user and password (CentOS)
  community.general.htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: 1234
  when: ansible_distribution == "CentOS"

- name: starting and enabling nagios (CentOS)
  service:
    name: nagios
    state: restarted
    enabled: true
  when: ansible_distribution == "CentOS"

- name: starting and enabling httpd (CentOS)
  service:
    name:  httpd
    state: restarted
    enabled: true
  when: ansible_distribution == "CentOS"
